# Reproduces issue https://github.com/facebookincubator/BOLT/issues/187
# The issue was triggered by buildCFG->postProcessIndirectBranches->
# addUnknownControlFlow invoked with a basic block that has multiple edges
# to the same successor.

RUN: mkdir -p %p/Output
RUN: test -f %p/Output/libpython3.8-pyston2.3.so.1.0.perf || \
RUN:   unzstd %p/Inputs/libpython3.8-pyston2.3.so.1.0.perf.zst \
RUN:   -o %p/Output/libpython3.8-pyston2.3.so.1.0.perf
RUN: test -f %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt || \
RUN:   unzstd %p/Inputs/libpython3.8-pyston2.3.so.1.0.prebolt.zst \
RUN:   -o %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt
RUN: perf2bolt -p %p/Output/libpython3.8-pyston2.3.so.1.0.perf -strict=0 \
RUN:   -skip-funcs=_PyEval_EvalFrame_AOT_Interpreter/1 \
RUN:   %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt -o %t.fdata -w %t.yaml

# Tests for fdata vs yaml from the same perf data
RUN: llvm-bolt -p %p/Output/libpython3.8-pyston2.3.so.1.0.perf \
RUN:   -skip-funcs=_PyEval_EvalFrame_AOT_Interpreter/1,_PyEval_EvalFrameDefault \
RUN:   %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt -o %t.null \
RUN:   --print-only=_PyEval_EvalCodeWithName.localalias/1,dict_dealloc --print-cfg \
RUN:   | FileCheck %s --check-prefix=CHECK-FUNC

RUN: llvm-bolt -data %t.fdata \
RUN:   -skip-funcs=_PyEval_EvalFrame_AOT_Interpreter/1,_PyEval_EvalFrameDefault \
RUN:   %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt -o %t.null \
RUN:   --print-only=_PyEval_EvalCodeWithName.localalias/1,dict_dealloc --print-cfg \
RUN:   | FileCheck %s --check-prefix=CHECK-FUNC

RUN: llvm-bolt -data %t.yaml \
RUN:   -skip-funcs=_PyEval_EvalFrame_AOT_Interpreter/1,_PyEval_EvalFrameDefault \
RUN:   %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt -o %t.null \
RUN:   --print-only=_PyEval_EvalCodeWithName.localalias/1,dict_dealloc --print-cfg \
RUN:   | FileCheck %s --check-prefix=CHECK-FUNC

CHECK-FUNC: Binary Function "dict_dealloc" after building cfg
CHECK-FUNC: Exec Count  : 6371

CHECK-FUNC: Binary Function "_PyEval_EvalCodeWithName.localalias/1(*2)" after building cfg
CHECK-FUNC: Successors: .Ltmp[[#]] (mispreds: 0, count: 1), .LFT[[#FT:]] (mispreds: 0, count: 10578)
CHECK-FUNC:      .LFT[[#FT]] (13 instructions, align : 1)
CHECK-FUNC-NEXT: Exec Count : 10578

# Test autofdo profile generation (-autofdo option)
RUN: perf2bolt -p %p/Output/libpython3.8-pyston2.3.so.1.0.perf \
RUN:   -skip-funcs=_PyEval_EvalFrame_AOT_Interpreter/1 \
RUN:   %p/Output/libpython3.8-pyston2.3.so.1.0.prebolt -o %t.afdo -autofdo
RUN: FileCheck %s --check-prefix=CHECK-AFDO --input-file %t.afdo
# LBR traces/fallthroughs: count, first record
CHECK-AFDO:      24587
CHECK-AFDO-NEXT: 119f8b-11a108:1
# Basic samples: count, first record
CHECK-AFDO:      59906
CHECK-AFDO-NEXT: 7f3073120fe0:1
# LBRs: count, first record
CHECK-AFDO:      28450
CHECK-AFDO-NEXT: 11a3d4->1c4f10:1
